import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home',
    games: 'Games',
    promotions: 'Promotions',
    news: 'News',
    contact: 'Contact Us',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    profile: 'Profile',
    admin_dashboard: 'Admin Dashboard',
    search_placeholder: 'Search games, gift cards...',
    popular_games: 'Popular Games',
    featured_games: 'Featured Games',
    categories: 'Categories',
    latest_news: 'Latest News & Guides',
    latest_promotions: 'Special Deals & Promotions',
    player_id: 'Player ID',
    server_id: 'Server ID',
    server_id_placeholder: 'Enter Server ID',
    player_id_placeholder: 'Enter Player ID',
    select_package: 'Select Top-Up Package',
    add_to_cart: 'Add To Cart',
    buy_now: 'Buy Now',
    cart: 'Shopping Cart',
    checkout: 'Checkout',
    price: 'Price',
    quantity: 'Quantity',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    apply_coupon: 'Apply Coupon',
    coupon_placeholder: 'Enter promo code',
    payment_method: 'Select Payment Method',
    upload_receipt: 'Upload Payment Receipt',
    upload_hint: 'Click or drag receipt image here to upload (PNG, JPG, max 5MB)',
    confirm_payment: 'Confirm Payment & Order',
    order_summary: 'Order Summary',
    game: 'Game',
    package: 'Package',
    status: 'Status',
    date: 'Date',
    order_no: 'Order No',
    my_orders: 'My Orders',
    transaction_history: 'Transaction History',
    change_password: 'Change Password',
    edit_profile: 'Edit Profile',
    save_changes: 'Save Changes',
    loading: 'Loading...',
    no_games_found: 'No games found matches your criteria.',
    all_categories: 'All Categories',
    phone: 'Phone Number',
    email: 'Email Address',
    full_name: 'Full Name',
    password: 'Password',
    confirm_password: 'Confirm Password',
    forgot_password: 'Forgot Password?',
    dont_have_account: "Don't have an account?",
    already_have_account: 'Already have an account?',
    order_pending: 'Pending Payment',
    order_waiting_verification: 'Waiting Verification',
    order_paid: 'Paid',
    order_processing: 'Processing Delivery',
    order_completed: 'Completed',
    order_cancelled: 'Cancelled',
    order_refunded: 'Refunded',
    payment_manual: 'Upload Manual Receipt',
    featured: 'Featured',
    bonus: 'Bonus',
    weekly_pass: 'Weekly Pass',
    monthly_pass: 'Monthly Pass',
    footer_text: '© 2026 Online Game Top-Up Platform. Secure & Instant Delivery.',
  },
  kh: {
    home: 'ទំព័រដើម',
    games: 'ហ្គេមទាំងអស់',
    promotions: 'ប្រូម៉ូសិន',
    news: 'ព័ត៌មានថ្មីៗ',
    contact: 'ទំនាក់ទំនងយើង',
    login: 'ចូលគណនី',
    register: 'ចុះឈ្មោះ',
    logout: 'ចាកចេញ',
    profile: 'គណនីរបស់ខ្ញុំ',
    admin_dashboard: 'ផ្ទាំងគ្រប់គ្រង Admin',
    search_placeholder: 'ស្វែងរកហ្គេម ឬកាតកាដូ...',
    popular_games: 'ហ្គេមពេញនិយម',
    featured_games: 'ហ្គេមណែនាំពិសេស',
    categories: 'ប្រភេទហ្គេម',
    latest_news: 'ព័ត៌មាន និងការណែនាំថ្មីៗ',
    latest_promotions: 'ការផ្តល់ជូនពិសេស & ប្រូម៉ូសិន',
    player_id: 'លេខសម្គាល់អ្នកលេង (Player ID)',
    server_id: 'លេខសម្គាល់ម៉ាស៊ីនបម្រើ (Server ID)',
    server_id_placeholder: 'បញ្ចូលលេខសម្គាល់ម៉ាស៊ីនបម្រើ',
    player_id_placeholder: 'បញ្ចូលលេខសម្គាល់អ្នកលេង',
    select_package: 'ជ្រើសរើសកញ្ចប់បញ្ចូលលុយ',
    add_to_cart: 'ដាក់ក្នុងកន្ត្រក',
    buy_now: 'ទិញភ្លាមៗ',
    cart: 'កន្ត្រកទិញទំនិញ',
    checkout: 'ការទូទាត់ប្រាក់',
    price: 'តម្លៃ',
    quantity: 'ចំនួន',
    subtotal: 'តម្លៃសរុបបណ្តោះអាសន្ន',
    discount: 'បញ្ចុះតម្លៃ',
    total: 'តម្លៃសរុប',
    apply_coupon: 'ប្រើប្រាស់កូដបញ្ចុះតម្លៃ',
    coupon_placeholder: 'បញ្ចូលកូដប្រូម៉ូសិន',
    payment_method: 'ជ្រើសរើសវិធីទូទាត់ប្រាក់',
    upload_receipt: 'បង្ហោះវិក្កយបត្របង់ប្រាក់',
    upload_hint: 'ចុច ឬអូសរូបភាពវិក្កយបត្របង់ប្រាក់ទីនេះ (PNG, JPG, ធំបំផុត 5MB)',
    confirm_payment: 'បញ្ជាក់ការបង់ប្រាក់ & បញ្ជាទិញ',
    order_summary: 'សេចក្តីសង្ខេបការបញ្ជាទិញ',
    game: 'ហ្គេម',
    package: 'កញ្ចប់',
    status: 'ស្ថានភាព',
    date: 'កាលបរិច្ឆេទ',
    order_no: 'លេខបញ្ជាទិញ',
    my_orders: 'ការបញ្ជាទិញរបស់ខ្ញុំ',
    transaction_history: 'ប្រវត្តិប្រតិបត្តិការ',
    change_password: 'ផ្លាស់ប្តូរពាក្យសម្ងាត់',
    edit_profile: 'កែសម្រួលព័ត៌មានផ្ទាល់ខ្លួន',
    save_changes: 'រក្សាទុកការផ្លាស់ប្តូរ',
    loading: 'កំពុងផ្ទុក...',
    no_games_found: 'រកមិនឃើញហ្គេមដែលត្រូវគ្នានឹងការស្វែងរករបស់អ្នកទេ។',
    all_categories: 'ប្រភេទទាំងអស់',
    phone: 'លេខទូរស័ព្ទ',
    email: 'អាសយដ្ឋានអ៊ីមែល',
    full_name: 'ឈ្មោះពេញ',
    password: 'ពាក្យសម្ងាត់',
    confirm_password: 'បញ្ជាក់ពាក្យសម្ងាត់',
    forgot_password: 'ភ្លេចពាក្យសម្ងាត់?',
    dont_have_account: 'មិនទាន់មានគណនីមែនទេ?',
    already_have_account: 'មានគណនីរួចហើយមែនទេ?',
    order_pending: 'រង់ចាំការទូទាត់',
    order_waiting_verification: 'កំពុងផ្ទៀងផ្ទាត់ការបង់ប្រាក់',
    order_paid: 'បានបង់ប្រាក់',
    order_processing: 'កំពុងបញ្ចូលទំនិញ',
    order_completed: 'បានជោគជ័យ',
    order_cancelled: 'បានបោះបង់',
    order_refunded: 'បានវេរលុយជូនវិញ',
    payment_manual: 'បង្ហោះវិក្កយបត្របង់ប្រាក់ដោយដៃ',
    featured: 'ណែនាំ',
    bonus: 'បន្ថែមជូន',
    weekly_pass: 'សំបុត្រប្រចាំសប្តាហ៍',
    monthly_pass: 'សំបុត្រប្រចាំខែ',
    footer_text: '© ២០២៦ វេទិកាបញ្ចូលលុយហ្គេមអនឡាញ។ សុវត្ថិភាព និងលឿនរហ័ស។',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
